### ISSUE TITLE
Spread the word 🗣️

### ISSUE THREAD

**Issue by joaomagfreitas** [cobrinhas/github-bookmark#1]
Did this tool help you in a positive way? If yes, tag someone you think would take advantage of the tool in the comments!  👇

**Comment by joaomagfreitas** [comment]
@rutesantos4

**Comment by joaomagfreitas** [comment]
@LuchoTurtle

**Comment by joaomagfreitas** [comment]
@nelsonic (Luís told me you would appreciate this extension :smile:)

**Comment by rutesantos4** [comment]
@RaquelCSantos
